export type RootStackParamList = {
  MainTabs: undefined;
  Login: undefined;
  Register: undefined;
  ForgotPassword: undefined;
  GlobalMap: { icon?: string; title?: string; type?: 'exercise' | 'fasting' | 'meditation' } | undefined;
  Sport: { key: string; icon: string; color: string; gps?: boolean };
  FastHistory: undefined;
  FastCalendar: undefined;
  MedHistory: undefined;
  MedCalendar: undefined;
  SleepHistory: undefined;
  PreceptHistory: undefined;
  FoodLog: undefined;
  Grace: undefined;
  StreakBreak: undefined;
  CheckinHistory: undefined;
  CheckinDetail: { date: string };
  ReviewHistory: undefined;
  ReviewDetail: { reviewId: string };
  ExerciseHistory: undefined;
  PlanCreate: { planId?: string; reflectionId?: string } | undefined;
  PlanDetail: { planId: string; addReflectionId?: string };
  PlanHistory: undefined;
  RecycleBin: undefined;
  PrivacyPolicy: undefined;
  Stats: undefined;
  ReflectionStats: undefined;
  MindTrail: undefined;
  QuickCreateTrail: { initialText?: string; selectedIds?: string[] } | undefined;
  ThoughtTrailDetail: { trailId: string };
  ReflectionDetail: { reflectionId: string };
  HabitDetail: { habitId: string };
  Music: undefined;
  MusicCategory: { category: string };
  RelationMap: { context: { type: string; id: string } } | undefined;
  AISettings: undefined;
  Profile: undefined;
  Insight: undefined;
  Review: { period: 'week' | 'month'; startDate: string; endDate: string } | undefined;
  StrategyLibrary: undefined;
};

export type MainTabParamList = {
  Home: undefined;
  Plan: undefined;
  Fasting: undefined;
  Practice: undefined;
  Meditation: undefined;
  Breathing: undefined;
  Sleep: undefined;
  Body: undefined;
  Precept: undefined;
  Vow: undefined;
  Sutra: undefined;
  Mantra: undefined;
  Exercise: undefined;
  Settings: undefined;
  Reflections: { showNew?: boolean; trailId?: string } | undefined;
  Habits: undefined;
  Diet: undefined;
  Mind: undefined;
};
